[package]
name = "unstacked"
version = "0.1.2"
edition = "2024"
description = "Lock-free, no-std concurrent stack for Rust"
license = "MIT"
readme = "README.md"
repository = "https://github.com/cestef/unstacked"
include = ["README.md"]
keywords = ["stack", "no-std", "concurrent"]
