on:
    push:
        branches:
            - main
env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: taiki-e/install-action@nextest
            - run: cargo nextest run